### ISSUE TITLE
Problem at making sonar server recognize custom rules

### ISSUE THREAD

**Issue by Ryudi** [gretard/sonar-tsql-plugin#21] opened 2018-12-12 18:29 UTC
Hello. I would like to know what do you mean exactly in this item of Wiki - Custom Rules:
> - Update sonar.tsql.customrules.paths settings in SonarQube server for TSQL plugin (please note, that on SonarQube server paths need to be absolute), i.e.:
> sonar.tsql.customrules.paths=C:\sonar-rules\
> sonar.tsql.customrules.paths=C:\sonar-rules\test.customRules,C:\sonar-rules\test2.customRules

Because when i run an analysis, the following message appears:

> WARN: Can't add issue AB1 on file .../WaitFor.sql at line 1.
> org.sonar.api.utils.MessageException: The rule 'tsqlDemoRepo:AB1' does not exist.

It is pointing right: An issue should be there because the rule is about restricting the use of WAIT FOR, which appears in WaitFor.sql. However the sonar server doesn't register because it couldn't recognize the rule.

![captura de tela 35](https://user-images.githubusercontent.com/14373138/49889829-a8912980-fe29-11e8-97e3-97b4a4ffec32.png)

The first line of .customRules file is `<sql-rules repoName="Demo rules" repoKey="tsqlDemoRepo">`.
As you can see the repo isn't there. I already tried to specify the parameter
 **sonar.tsql.customrules.paths** in the file sonarqube-7.4\conf\sonar.properties and in the Sonar UI:

![captura de tela 36](https://user-images.githubusercontent.com/14373138/49889626-299bf100-fe29-11e8-979f-25860d4a3f8a.png)

None of them worked. I am supposed to specify it somewhere else?

**Comment by gretard** [comment] 2018-12-12 22:17
Hi,

Thank you for raising this, did you restart Sonarqube after adding the
rules? I will try to reproduce this issue in the meantime :) Because from
the logs it seems that sonar-scanner was able to find the rules, but
Sonarqube server -no. Did you physically put those rules files to the
specified path on the SonarQube machine?

Greta

**Comment by Ryudi** [comment] 2018-12-13 12:52
Yes, i did try restarting the server. One thing i noticed: I restarted SonarQube fresh (downloaded it again), then i tried changing sonar.tsql.customrules.paths only in the Sonar UI, but not in the sonar.properties file. I couldn't restart the server after that, because StartSonar.bat started to catch a Java.io.IOException. I had to set it in sonar.properties too so the server could be up again. My issue persisted though. Where exactly am i supossed to set sonar.tsql.customrules.paths on the server side?

The .customRules file referenced is supposed to be the exact same (same content at least) both in the server and in the client, right? For now, since i am running both sides in the same machine, i am making both to reference the same .customRules file, but the issue still happens.

The 4 T-SQL rules repositories that already are there were added through the sonarqube-7.4\extensions\plugins\sonar-tsql-plugin-0.8.2.jar, so am i not supposed to do something similar and add another .jar containing a new rule repository?

Another unrelated note: The attribute sonar.tsql.customrules.prefix is named wrong i assume, because .customRules is a filename suffix, not prefix.

**Comment by gretard** [comment] 2018-12-13 21:16
Hi,

Could you send the java.io exception details? As you are running on the same machine server and scanner, I would suggest only setting property **sonar.tsql.customrules.paths** in the Administration UI to the full path, for example: _C:\Users\test\Desktop\custom-Rules\myExampleRepo.customRules_. Then try to restart SonarQube server and check in logs if you see something like: 

`
2018.12.13 22:57:24 INFO  web[][o.s.p.t.r.d.CustomUserChecksProvider] Read 2 rules ok at: C:\Users\test\Desktop\custom-Rules\myExampleRepo.customRules
`

This means that SonarQube server was able to find rules descriptions and they should be seen in the UI->Rules section.

After sorthing this, on the sonar scanner side, I would suggest removing property _sonar.tsql.customrules.paths_ from **sonar-project.properties** at all as you are running server and scanner on the same machine and then this property will get picked from the server. 

They reason why this is so complicated as usually sonar server runs and analysis is triggered on different machines. So SonarQube server needs to know about custom rules, so they need to be on the Sonarqube's server file system. That's why you need to specify that setting in the UI and restart server, so that it would know where they are. And when running analysis - sonar scanner also needs to know about the custom rules. So if your rules reside on a different path than on server - then you need to override that _sonar.tsql.customrules.paths_ setting in the  **sonar-project.properties** file, so that sonar scanner could read the rules, execute then and submit results to the server.
All, in all I hope this will help. In the next release I am planning to check and add support for adhoc rules if possible, so that this would not be so complicated 😊

**Comment by Ryudi** [comment] 2018-12-14 16:01
So this is what happens when i set _sonar.tsql.customrules.paths_ only in the Sonar server UI and not on sonar.properties file:

![captura de tela 37](https://user-images.githubusercontent.com/14373138/50000957-64656c80-ff82-11e8-8ae9-4a4a34b48d2d.png)

jvm 1    | java.io.IOException: Foi forþado o cancelamento de uma conexÒo existente pelo host remoto
(**Translation:** Internal Exception: java.io.IOException: an existing connection was forcibly closed by a remote host)
jvm 1    |      at sun.nio.ch.SocketDispatcher.read0(Native Method)
jvm 1    |      at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
jvm 1    |      at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
jvm 1    |      at sun.nio.ch.IOUtil.read(IOUtil.java:192)
jvm 1    |      at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
jvm 1    |      at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:433)
jvm 1    |      at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
jvm 1    |      at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
jvm 1    |      at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
jvm 1    |      at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
jvm 1    |      at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
jvm 1    |      at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
jvm 1    |      at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
jvm 1    |      at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
jvm 1    |      at java.lang.Thread.run(Thread.java:748)
jvm 1    | 2018.12.14 09:29:10 WARN  app[][o.e.t.n.Netty4Transport] exception caught on transport layer [[id: 0x8168716c, L:/127.0.0.1:55852 - R:/127.0.0.1:9001]], closing connection

**Comment by gretard** [comment] 2018-12-14 16:05
Hi, could you check what exception is shown in the web.log file at /bin/logs directory?

**Comment by gretard** [comment] 2018-12-22 15:07
Closing this as new version supports simplified process of using custom rules via adhoc rules. You can check example at [example4-adhoc](https://github.com/gretard/sonar-tsql-plugin/tree/master/examples/example4-adhoc)

**Closed by gretard** 2018-12-22 15:07 UTC
